INSERT INTO contractors (
  id,
  business_name,
  contact_name,
  email,
  phone,
  industry,
  sub_service,
  zip_codes,
  username,
  password_hash,
  sms_opt_in,
  wallet_balance,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Test Contractor 1',
  'John Smith',
  'test1@example.com',
  '(555) 123-4567',
  'home_services',
  'plumbing',
  ARRAY['12345'],
  'test1@example.com',
  '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
  true,
  100.00,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Test Contractor 2',
  'Jane Doe',
  'test2@example.com',
  '(555) 234-5678',
  'home_services',
  'hvac',
  ARRAY['12346'],
  'test2@example.com',
  '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
  true,
  75.00,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Test Contractor 3',
  'Bob Johnson',
  'test3@example.com',
  '(555) 345-6789',
  'legal',
  'personal_injury',
  ARRAY['12347'],
  'test3@example.com',
  '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
  true,
  50.00,
  NOW(),
  NOW()
) ON CONFLICT (username) DO NOTHING;
